server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

#  关闭spring图标
  main:
    banner-mode: off


#springboot mybatis整合 yaml配置
mybatis:
#  扫描映射文件
  mapper-locations: classpath:mapper/*.xml
#  别名扫描的包
  type-aliases-package: com.itheima.domain
  configuration:
    #    开启日志
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    关闭日志
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

    #开启mybatis 驼峰式命名规则自动转换功能
#    map-underscore-to-camel-case: true

