server:
#端口
  port: 8080

#数据库资源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    banner-mode: off  #闭springboot图标
  devtools:
    restart:
      exclude: config/**,static/**  #自定义不参与热部署的文件或文件夹
      enabled: false    #关闭热部署，但是可能被优先级高的配置覆盖

mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml   #  设置xml映射地址
#  type-aliases-package: com.itheima.domain   #  设置mybatis对应实体类包地址
  configuration:
     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl      # 开启日志
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl     # 关闭日志
  global-config:
    banner: off   #    关闭mybatis日志
    db-config:
      table-prefix: tbl_    # 数据库表名前缀
      id-type: auto   #id自增
#    mybatisPlus会自动开启驼峰命名转换，如果在实体类中设置好了，这里需要更改为false
#    map-underscore-to-camel-case: false





